kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mind-rot/dbfs

steps:
- name: build
  image: golang:1.12.6-alpine3.9
  commands:
  - GO111MODULE=on CGO_ENABLED=0 go build -mod vendor ./...
  - go test

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_name
    password:
      from_secret: docker_password
    repo: mindrot/dbfs
    
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 68.183.210.229
    port: 22
    ssh_key:
      from_secret: ssh_key
    script:
    - cd /srv/dbfs
    - docker-compose up -d
