kind: pipeline
name: default

workspace:
  base: /go
  src: src/github.com/mind-rot/dbfs

steps:
- name: build
  image: golang:1.12.5-alpine3.9
  commands:
  - pwd
  - ls
  - go build .

- name: deploy
  image: appleboy/drone-ssh
  environment:
    SSH_KEY:
      from_secret: ssh_key
  settings:
    host: 68.183.210.229
    port: 22
    envs: [ SSH_KEY ]
    script:
    - echo "test ssh"
    - echo $SSH_KEY
    # secrets: [ ssh_key ]
