kind: pipeline
name: default

workspace:
  base: /go
  src: src/github.com/mind-rot/dbfs

steps:
- name: build
  image: golang:1.12.5
  commands:
  - go build
  - go test

- name: docker
  image: plugins/docker
  environment:
    docker_name:
      from_secret: docker_name
    docker_password:
      from_secret: docker_password
  settings:
    username: docker_name
    password: docker_password
    repo: mindrot/dbfs

- name: deploy
  image: appleboy/drone-ssh
  environment:
    SSH_KEY:
      from_secret: ssh_key
  settings:
    host: 68.183.210.229
    port: 22
    envs: [ SSH_KEY ]
    script:
    - pwd
    - ls
    - cd /srv/dbfs
    - docker-compose pull
    - docker-compose up
