kind: pipeline
name: default

workspace:
  base: /go
  src: src/github.com/mind-rot/dbfs

steps:
- name: build
  image: golang:1.12.5
  commands:
  - go build
  - go test

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_name
    password:
      from_secret: docker_password
    repo: mindrot/dbfs

- name: deploy
  image: appleboy/drone-ssh
  # environment:
  #   SSH_KEY:
  #     from_secret: ssh_key
  settings:
    host: 68.183.210.229
    port: 22
    ssh_key:
      from_secret: ssh_key
    # envs: [ SSH_KEY ]
    script:
    - pwd
    - ls
    - cd /srv/dbfs
    - docker-compose pull
    - docker-compose up
