kind: pipeline
name: default

workspace:
  base: /go
  src: src/github.com/mind-rot/dbfs

steps:
- name: build
  image: golang:1.12.5-alpine3.9
  commands:
  - pwd
  - ls
  - go build .

- name: deploy
  image: appleboy/drone-ssh
  host: "http://68.183.210.229"
  username: root
  secrets: [ ssh_key ]
  script:
  - echo "test ssh"
